version: '3'

services:
  web:
    build: .
    ports:
      - "4000:80"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: new
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
# Uncomment in case of using clickhouse
#     depends_on:
#       - clickhouse
#     networks:
#       - webnet

#   clickhouse:
#     image: yandex/clickhouse-server
#     ports:
#       - "8123:8123" # Expose the default ClickHouse HTTP interface port
#       - "9000:9000" # Optional: expose the native client-server TCP interface port
#     volumes:
#       - clickhouse_data:/var/lib/clickhouse # Persist data
#     networks:
#       - webnet

# networks:
#   webnet:

# volumes:
#   clickhouse_data:

